-- CreateTable
CREATE TABLE `philosopher_protectors` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(191) NOT NULL,
    `description` TEXT NOT NULL,
    `phrase` TEXT NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- Seed philosopher protectors (59 entries, men and women)
INSERT INTO `philosopher_protectors` (`name`, `description`, `phrase`) VALUES
('Sócrates', 'Ateniense que valorizava o diálogo e o exame da própria vida.', 'Pergunte antes de afirmar, e o caminho clareia.'),
('Djamila Ribeiro', 'Filósofa brasileira, expoente do feminismo crítico.', 'Conheça seu lugar de fala para ampliar o diálogo.'),
('Platão', 'Fundador da Academia, buscou as ideias por trás do mundo visível.', 'Olhe além do imediato e enxergue o que permanece.'),
('Aristóteles', 'Sistematizou o conhecimento e defendeu a virtude como hábito.', 'Faça o bem pequeno todos os dias e ele vira caráter.'),
('bell hooks', 'Pensadora da pedagogia do amor e interseccionalidade.', 'O amor é uma ação, não apenas um sentimento.'),
('Epicuro', 'Defendeu prazeres simples e a calma da alma.', 'Simplifique o desejo e o sossego aparece.'),
('Sêneca', 'Estoico romano que ensinou força interior e lucidez.', 'Controle o que depende de você e solta o resto.'),
('Angela Davis', 'Ativista e filósofa da liberdade e abolição.', 'Não basta não ser racista, é preciso ser antirracista.'),
('Marco Aurélio', 'Imperador estoico, escreveu sobre disciplina e humanidade.', 'Aja com retidão, mesmo quando ninguém vê.'),
('Epicteto', 'Ex-escravo estoico que ensinou liberdade interior.', 'Sua resposta é sua verdadeira liberdade.'),
('Christine de Pizan', 'Pioneira na defesa das mulheres na Idade Média.', 'Construa sua própria cidade de argumentos e valores.'),
('Cínicos (Diógenes)', 'Crítico das convenções, buscou autenticidade radical.', 'Corte o excesso e viva com o essencial.'),
('Santa Hildegarda de Bingen', 'Mística, erudita e visionária medieval.', 'Busque o equilíbrio entre o corpo, a mente e a natureza.'),
('Agostinho', 'Pensador cristão que uniu fé e razão.', 'Escute o coração sem abandonar a clareza.'),
('Judith Butler', 'Teórica do gênero e da performance social.', 'Questione os papéis que a sociedade espera que você atue.'),
('Tomás de Aquino', 'Sintetizou fé e razão na Idade Média.', 'Ordene o pensamento e a ação encontra rumo.'),
('Maquiavel', 'Analista político realista do poder.', 'Veja o mundo como é para agir com prudência.'),
('Nancy Fraser', 'Filósofa da justiça redistributiva e reconhecimento.', 'Lute por pão, mas também por respeito e dignidade.'),
('Descartes', 'Pai do racionalismo moderno.', 'Duvidar com método é caminho para a certeza.'),
('Spinoza', 'Defendeu a ética da alegria e da potência.', 'Conheça suas causas e você se liberta.'),
('Hannah Arendt', 'Refletiu sobre política, ação e banalidade do mal.', 'Pense por si e recuse a inércia.'),
('Hobbes', 'Pensou o contrato social e a ordem civil.', 'Acordos claros evitam conflitos longos.'),
('Simone de Beauvoir', 'Feminista existencialista, pensou liberdade e responsabilidade.', 'Liberdade exige ação concreta hoje.'),
('Locke', 'Defendeu direitos naturais e liberdade.', 'Respeite limites e crie confiança.'),
('Hume', 'Cético sobre certezas, valorizou a experiência.', 'Teste na prática antes de crer de vez.'),
('Rousseau', 'Criticou desigualdades e pensou a vontade geral.', 'Busque o comum sem apagar o singular.'),
('Rosa Luxemburgo', 'Teórica marxista e defensora da liberdade democrática.', 'Liberdade é sempre a liberdade de quem pensa diferente.'),
('Kant', 'Defendeu o dever e a dignidade humana.', 'Escolha o que você gostaria que virasse regra.'),
('Hegel', 'Pensou a história como movimento de ideias.', 'Encare o conflito como chance de síntese.'),
('Bettisia Gozzadini', 'Jurista medieval, primeira mulher a lecionar em universidade.', 'Ocupe espaços de saber com competência e coragem.'),
('Schopenhauer', 'Viu o desejo como fonte de dor.', 'Reduza a vontade e cresce a serenidade.'),
('Nietzsche', 'Crítico da moral tradicional, exaltou a criação.', 'Crie seus próprios valores com coragem.'),
('Novella d’Andrea', 'Estudiosa de Direito que ensinava por trás de um véu.', 'Sua voz e seu conhecimento valem mais que sua aparência.'),
('Kierkegaard', 'Pensador do indivíduo e da escolha.', 'Assuma sua decisão e ela ganha sentido.'),
('Bergson', 'Valorizou a intuição e o tempo vivido.', 'Sinta o ritmo da vida antes de acelerar.'),
('Trotula de Salerno', 'Médica e pioneira na saúde feminina medieval.', 'Cuide da saúde das mulheres como um ato de resistência.'),
('Simone de Beauvoir', 'Feminista existencialista, pensou liberdade e responsabilidade.', 'Liberdade exige ação concreta hoje.'),
('Hannah Arendt', 'Refletiu sobre política, ação e banalidade do mal.', 'Pense por si e recuse a inércia.'),
('Dorotea Bucca', 'Ocupou a cátedra de medicina por 40 anos na Renascença.', 'A constância no estudo abre portas antes fechadas.'),
('Edith Stein', 'Filósofa fenomenóloga e ética da empatia.', 'Compreenda o outro para agir com justiça.'),
('Simone Weil', 'Pensadora do sofrimento e da atenção.', 'Atenção genuína é uma forma de cuidado.'),
('Lélia Gonzalez', 'Antropóloga e filósofa do feminismo negro amefricano.', 'Reconheça sua ancestralidade para entender seu presente.'),
('Mary Wollstonecraft', 'Defendeu educação e direitos para as mulheres.', 'Eduque-se para não pedir permissão.'),
('Hypátia de Alexandria', 'Matemática e filósofa da Antiguidade.', 'Cultive estudo e clareza, mesmo sob ruído.'),
('Sueli Carneiro', 'Filósofa e ativista, voz do "ennegrecer" o feminismo.', 'Use o conhecimento como ferramenta de transformação social.'),
('Confúcio', 'Pensador chinês da ética e harmonia social.', 'Respeito cotidiano cria paz duradoura.'),
('Laozi', 'Autor associado ao Tao Te Ching.', 'Agir sem forçar abre caminhos.'),
('Marilena Chaui', 'Especialista em Espinosa e crítica da ideologia.', 'Não aceite o óbvio; questione o que parece natural.'),
('Zhuangzi', 'Taoísta que celebrou a liberdade interior.', 'Solte a rigidez e respire mais leve.'),
('Buda (Siddhartha Gautama)', 'Ensinou o caminho do meio e a compaixão.', 'Reduza o apego e a mente se aquieta.'),
('Viviane Mosé', 'Filósofa que aproxima a filosofia da vida cotidiana.', 'Aprenda a viver a incerteza com mais leveza.'),
('Nagarjuna', 'Filósofo do budismo Mahayana.', 'Não se prenda a certezas fixas.'),
('Sun Tzu', 'Autor de A Arte da Guerra.', 'Planeje em silêncio e aja no tempo certo.'),
('Paulo Freire', 'Filósofo da educação e da autonomia.', 'A leitura do mundo precede a leitura da palavra.'),
('Ibn Sina (Avicena)', 'Filósofo e médico persa.', 'Integre razão e experiência no seu cuidado.'),
('Ibn Rushd (Averróis)', 'Defendeu a razão como aliada da fé.', 'Busque coerência entre crença e ação.'),
('Ailton Krenak', 'Pensador indígena sobre a vida e a natureza.', 'Adie o fim do mundo através do afeto e da escuta.'),
('Al-Farabi', 'Pensou a cidade virtuosa e a música.', 'Harmonia interna melhora o convívio externo.'),
('Al-Ghazali', 'Crítico do excesso de racionalismo.', 'Humildade intelectual abre novas respostas.'),
('Cida Bento', 'Psicóloga e filósofa do "pacto da branquitude".', 'Identifique privilégios invisíveis para gerar equidade.'),
('Maimônides', 'Judeu medieval, conciliou fé e filosofia.', 'Clareza de princípios evita ansiedade.'),
('Foucault', 'Analisou poder e discursos.', 'Questione as regras invisíveis do dia.'),
('Geni Núñez', 'Pensadora sobre não-monogamia e anticolonialismo.', 'Descolonize seus afetos e suas formas de amar.'),
('Sartre', 'Existencialista que afirmou a liberdade radical.', 'Escolha agora e assuma as consequências.'),
('Camus', 'Pensou o absurdo e a revolta.', 'Diga sim à vida mesmo sem garantias.'),
('Mário Sergio Cortella', 'Filósofo da ética e da gestão existencial.', 'Faça o seu melhor nas condições que você tem hoje.'),
('Merleau-Ponty', 'Filósofo do corpo e da percepção.', 'Escute o corpo antes da pressa mental.'),
('Heidegger', 'Refletiu sobre o ser e o tempo.', 'Pare e repare no que realmente importa.'),
('Luiz Felipe Pondé', 'Filósofo do cotidiano e do niilismo contemporâneo.', 'Encare a realidade sem o filtro do otimismo ingênuo.'),
('Wittgenstein', 'Investigou limites da linguagem.', 'Fale simples para pensar melhor.'),
('Popper', 'Defendeu a crítica e a falseabilidade.', 'Teste suas ideias com coragem.'),
('Clovis de Barros Filho', 'Pensador da ética e da vida que vale a pena.', 'A felicidade é o instante que você não quer que acabe.'),
('Rawls', 'Pensou justiça como equidade.', 'Pense na regra como se fosse para todos.'),
('Freire', 'Educador e filósofo brasileiro da libertação.', 'Dialogar transforma quem ensina e aprende.'),
('Márcia Tiburi', 'Filósofa da estética e do diálogo político.', 'Dialogar é o oposto de tentar aniquilar o outro.'),
('Nise da Silveira', 'Psiquiatra humanista, valorizou arte e afeto.', 'Cuidar com afeto libera potência.'),
('Djamila Ribeiro', 'Filósofa brasileira do lugar de fala.', 'Escute com atenção e fale com responsabilidade.'),
('Katiúscia Ribeiro', 'Filósofa focada em Filosofia Africana (Kemética).', 'Resgate valores ancestrais para curar o futuro.'),
('Lélia Gonzalez', 'Intelectual brasileira da cultura e raça.', 'Reconheça diferenças e fortaleça o comum.'),
('Judith Butler', 'Filósofa sobre gênero e performatividade.', 'Reveja padrões e escolha os seus.'),
('Dora Incontri', 'Filósofa da educação e espiritualidade racional.', 'Eduque para a liberdade de espírito e o senso crítico.'),
('Angela Davis', 'Ativista e pensadora da liberdade.', 'Organize-se com outros e a mudança vem.'),
('Evaristo de Miranda', 'Filósofo e cientista focado na ecologia humana.', 'Cultive a terra e a alma com a mesma dedicação.'),
('Martha Nussbaum', 'Defende capacidades e justiça humana.', 'Cultive capacidades que ampliem sua vida.'),
('Oswaldo Giacoia Jr.', 'Maior especialista brasileiro em Nietzsche.', 'Transforme sua dor em potência criativa e afirmação.'),
('Amartya Sen', 'Economista e filósofo das liberdades.', 'Liberdade cresce quando você remove barreiras.'),
('Vladimir Safatle', 'Filósofo da política e da psicanálise.', 'A liberdade surge quando perdemos o medo do conflito.'),
('bell hooks', 'Pensadora do amor e da educação crítica.', 'Ame com responsabilidade e coragem.'),
('Ynaê Lopes dos Santos', 'Historiadora e pensadora das relações raciais.', 'Entenda o passado para não repetir erros no presente.'),
('Ailton Krenak', 'Pensador indígena brasileiro.', 'Escute a terra e reduza o excesso.'),
('Silvio Almeida', 'Filósofo do direito e do racismo estrutural.', 'As estruturas sociais exigem mudanças, não apenas indivíduos.'),
('Eduardo Giannetti', 'Filósofo e economista, pensa o autoengano.', 'Seja honesto com suas próprias motivações internas.'),
('Clóvis de Barros Filho', 'Filósofo brasileiro da ética do cotidiano.', 'O que você faz hoje vira seu caráter amanhã.');
