-- CreateTable
CREATE TABLE `jokes` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `text` TEXT NOT NULL,
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- Seed jokes (pergunta + quebra de linha + resposta)
INSERT INTO `jokes` (`id`, `text`) VALUES
(1, 'Você conhece a piada do pônei?\nPô nei eu!'),
(2, 'O que o pagodeiro foi fazer na igreja?\nCantar pá God.'),
(3, 'O que o pato falou para a pata?\nVem quá!'),
(4, 'Você sabe qual é o rei dos queijos?\nO reiqueijão!'),
(5, 'O que acontece quando chove na Inglaterra?\nVira Inglalama!'),
(6, 'O que o tomate foi fazer no banco?\nTirar extrato!'),
(7, 'Como se chama a pessoa que viu o Thor de perto?\nVi-Thor!'),
(8, 'Por que a velhinha não usa relógio?\nPorque ela é sem hora (senhora)!'),
(9, 'Por que há uma cama elástica no polo Norte?\nPara o urso polar!'),
(10, 'O que a vaca disse para o boi?\nTe amuuuuuuuuuu!'),
(11, 'Um caipira chega à casa de um amigo que está vendo TV e pergunta: \"E aí, firme?\"\nNão, futebor!'),
(12, 'A plantinha foi ao hospital, mas não foi atendida. Por quê?\nPorque lá só tinha médico de plantão!'),
(13, 'Você conhece o site do cavalinho?\nwww ponto cavalinho ponto com ponto com ponto com ponto com ponto com!'),
(14, 'Quando os americanos comeram carne pela primeira vez?\nQuando chegou Cristóvão \"Com Lombo\"!'),
(15, 'Estou tão sem grana que até a minha última conversa foi fiada.\n'),
(16, 'O farmacêutico perguntou se eu tinha receita.\nRespondi que se eu tivesse a receita, faria o remédio em casa!'),
(17, 'Amor, o padre que casou a gente morreu.\nBem feito. Aqui se faz, aqui se paga!'),
(18, 'Qual é a maior injustiça do Natal?\nÉ o peru que morre e a missa é do galo!'),
(19, 'Por que o peixe não usa computador?\nPorque tem medo de pescar vírus!'),
(20, 'O que a borboleta disse para a mãe?\nMãe, para de me enrolar!'),
(21, 'Por que o esqueleto não tem amigos?\nPorque não tem corpo pra ninguém!'),
(22, 'Por que o espantalho ganhou um prêmio?\nPorque ele era excepcional no seu campo!'),
(23, 'O que a caneta disse para o papel?\nVocê me deixa sem palavras!'),
(24, 'Qual fruta dança melhor?\nA maçã, porque ela tem ritmo na casca!'),
(25, 'O que o macarrão disse ao molho?\nVocê me completa!'),
(26, 'Por que o astronauta não passa fome?\nPorque sempre tem um lanche no espaço!'),
(27, 'Por que o elefante tirou nota dez?\nPorque nunca esquece a matéria!'),
(28, 'O que o cachorro foi fazer na faculdade?\nTirar um doutorado em late!'),
(29, 'Por que a galinha atravessou a rua?\nPorque era o lado de cá que estava do outro lado!'),
(30, 'Por que o bolo estava chorando?\nPorque a vida é uma mistura de alegria e farinha!'),
(31, 'O que o piolho disse quando chegou na cabeça do milionário?\nFinalmente cheguei ao topo!'),
(32, 'Por que a cobra foi mal na prova?\nPorque ela enrolou muito!'),
(33, 'O que a janela disse para a porta?\nVocê está sempre me dando passagem!'),
(34, 'Por que a cebola é a atriz favorita dos cozinheiros?\nPorque sempre faz todo mundo chorar!'),
(35, 'O que o mágico disse quando errou o truque?\nPasse bem!'),
(36, 'Por que não se deve confiar no termômetro?\nPorque ele tem grau de falsidade!'),
(37, 'Por que a tartaruga não pega ônibus?\nPorque ela já vive na concha!'),
(38, 'O que o músico vegano come?\nBeterraba (beter-rock)!'),
(39, 'O que o pão francês faz no 7 de setembro?\nDesfila!'),
(40, 'O que a escada disse ao elevador?\nVocê me superou em todos os andares!'),
(41, 'Por que o caracol é sempre o último a chegar?\nPorque ele carrega o trabalho nas costas!'),
(42, 'O que a vassoura disse pra vida?\nTô varrendo qualquer problema!'),
(43, 'Por que o leão não usa celular?\nPorque já tem garras de sinal!'),
(44, 'O que a pizza disse para o garçom?\nPara de me fatiar a vida!'),
(45, 'Por que o polvo é bom em tudo?\nPorque ele tem mão pra tudo!'),
(46, 'Por que o vento perdeu o emprego?\nPorque só sabia soprar canudo!'),
(47, 'O que o pinguim foi fazer no deserto?\nDerreter de vergonha!'),
(48, 'O que o telescópio disse para o microscópio?\nVocê enxerga longe... para dentro!'),
(49, 'O que o navio disse quando parou?\nÂncora vez!'),
(50, 'Por que a geladeira não dorme?\nPorque fica sempre com a luz acesa!');

