-- Seed additional jokes (51–149)
INSERT INTO `jokes` (`id`, `text`) VALUES
(51, 'O que o sapo disse quando virou prefeito?\nAgora quem manda sou eu, ribbit!'),
(52, 'Por que o computador foi ao médico?\nPorque estava com vírus e não processava mais nada!'),
(53, 'O que a abelha disse para a flor?\nVocê adoça meu dia!'),
(54, 'Por que a nuvem nunca chega no horário?\nPorque ela sempre está na neblina!'),
(55, 'O que o pato disse quando aprendeu a cozinhar?\nAgora sim, tô no molho!'),
(56, 'O que o relógio disse para o calendário?\nVocê me atrasa!'),
(57, 'O que a cenoura disse para o coelho?\nOlha quem vem me buscar de novo!'),
(58, 'Por que o pato foi ao cinema sozinho?\nPorque ninguém quis ir quá ele!'),
(59, 'O que o abacate disse quando ficou famoso?\nGuaca, guaca, guaca... eu virei mole!'),
(60, 'O que o fusível disse antes de queimar?\nPelo menos minha vida teve brilho!'),
(61, 'O que o espelho disse para a parede?\nVocê não tem reflexo nenhum!'),
(62, 'Por que o dentista é sempre feliz?\nPorque ele lida com sorrisos o dia todo!'),
(63, 'O que a banana disse quando caiu?\nEscorreguei de vez!'),
(64, 'Por que o avião ficou vermelho?\nPorque viu a pista de pouso!'),
(65, 'Por que o biscoito estava triste?\nPorque todo mundo queria o seu lado recheado!'),
(66, 'O que o cachorro faz numa festa?\nLate night!'),
(67, 'O que o travesseiro disse para o cobertor?\nJuntos somos mais quentes!'),
(68, 'Qual animal é bom em matemática?\nO gambá, porque é ás!'),
(69, 'O que o sapato disse para o pé?\nPara de me apertar!'),
(70, 'O que a melancia foi fazer na praia?\nSe refrescar!'),
(71, 'Por que o cogumelo é sempre convidado para as festas?\nPorque ele é um fungo divertido!'),
(72, 'Por que o frango não joga xadrez?\nPorque tem medo de perder as peças!'),
(73, 'Por que a minhoca é boa aluna?\nPorque ela sempre está no fundo da terra firme!'),
(74, 'O que o arroz disse para o feijão?\nSem você, minha vida não tem caldo!'),
(75, 'Por que a bola de futebol é feliz?\nPorque é chutada, mas nunca abandonada!'),
(76, 'Por que o peixe nunca guarda segredo?\nPorque tem memória de peixe!'),
(77, 'Por que a lagartixa subiu no telhado?\nPorque queria uma visão de cima (gecko)!'),
(78, 'O que a borracha disse para o lápis?\nVivo apagando seus erros!'),
(79, 'Por que a televisão foi ao psicólogo?\nPorque vivia mudando de canal sem saber o que queria!'),
(80, 'O que o gato disse ao cachorro?\nA diferença entre nós é que eu escolho quando quero atenção!'),
(81, 'O que a pipoca disse quando o filme ficou chato?\nPelo menos eu estouro de animação!'),
(82, 'O que o rato foi fazer na biblioteca?\nRoer os livros de história!'),
(83, 'O que a aranha disse quando terminou a teia?\nMinha vida está bem tecida!'),
(84, 'O que a chave disse para a fechadura?\nVocê me abre pra qualquer coisa!'),
(85, 'Por que o coelho ganhou a maratona?\nPorque ele veio de longe pulando!'),
(86, 'O que o sanduíche disse para o hambúrguer?\nVocê está se achando muito!'),
(87, 'Por que o tucano é o pássaro mais estiloso?\nPorque tem bico de designer!'),
(88, 'O que o suco de laranja disse de manhã?\nBom dia, espremido de acordar!'),
(89, 'O que o sino disse quando bateu errado?\nErrei o tom mas acertei na hora!'),
(90, 'O que o telhado disse para a casa?\nEu te cubro em qualquer situação!'),
(91, 'Por que a chuva nunca é pontual?\nPorque ela vem em qualquer momento que quer!'),
(92, 'O que a pedra disse para o sapato?\nEntrei na sua vida de repente, né?'),
(93, 'Por que a baleia não vai ao dentista?\nPorque tem medo de abrir a boca na água!'),
(94, 'O que a esponja disse quando foi espremida?\nChega, estou seca de tanto absorver problema!'),
(95, 'O que o ovo disse para a frigideira?\nVocê me esquenta demais!'),
(96, 'Por que a girafa não usa cachecol?\nPorque ficaria longa demais a história!'),
(97, 'O que a cama disse para o despertador?\nPara de me sabotar!'),
(98, 'Por que a formiga nunca tira férias?\nPorque tem muito trabalho para formigar!'),
(99, 'Por que o sinal de trânsito é indeciso?\nPorque fica mudando de cor a toda hora!'),
(100, 'O que o chapéu disse para a chuva?\nPode vir, eu já estou em cima de tudo!'),
(101, 'Por que o queijo suíço tem tantos buracos?\nPorque é muito bem ventilado!'),
(102, 'O que a lâmpada disse quando foi instalada?\nAgora sim, vou iluminar minha carreira!'),
(103, 'Por que o calendário fica nervoso em dezembro?\nPorque sabe que seus dias estão contados!'),
(104, 'O que o fogão disse para o micro-ondas?\nEu aqui faço tudo com calma, com fogo baixo!'),
(105, 'O que o grampo disse para as folhas?\nVocês não vão a lugar nenhum sem mim!'),
(106, 'O que o tapete disse para a vassoura?\nVocê me tira do sério toda vez!'),
(107, 'Por que a maçaneta é a mais popular da casa?\nPorque todo mundo passa por ela!'),
(108, 'O que a gravata disse para a camisa?\nVocê me dá muito suporte!'),
(109, 'O que o martelo disse para o prego?\nVocê me dá na cabeça!'),
(110, 'O que o ventilador disse para o verão?\nEu giro em torno de você!'),
(111, 'O que o fio dental disse para o dente?\nVou passar por tudo isso com você!'),
(112, 'O que a abelha pediu no restaurante?\nUm mel de entrada e flores de sobremesa!'),
(113, 'O que o rádio disse para a TV?\nAntes eu era quem animava as festas!'),
(114, 'O que o parafuso disse para a chave de fenda?\nVocê me deixa girando!'),
(115, 'O que o porta-retratos disse para a fotografia?\nVocê me enquadra perfeitamente!'),
(116, 'Por que a impressora entrou em greve?\nPorque estava farta de trabalhar sob pressão!'),
(117, 'O que o mouse disse para o teclado?\nJuntos clicamos bem!'),
(118, 'Por que a bússola foi ao psicólogo?\nPorque não sabia mais para onde se virar!'),
(119, 'Por que o liquidificador não tem amigos?\nPorque bate em tudo que aparece!'),
(120, 'O que a escova disse para os dentes toda manhã?\nBora, temos muito pela frente!'),
(121, 'O que a cueca disse quando saiu da lavagem?\nEncolhi, mas não desisti!'),
(122, 'O que o sorvete disse no verão?\nEsse calor me desfaz!'),
(123, 'Por que o espaguete foi ao médico?\nPorque estava muito enrolado!'),
(124, 'O que o semáforo disse para o motorista impaciente?\nDá uma pausa, cara!'),
(125, 'O que a porta disse para a janela?\nQuando uma fecha, a outra abre!'),
(126, 'O que o pente disse ao careca?\nCom você não tem saída pra mim!'),
(127, 'Por que o espelho é o mais honesto da casa?\nPorque sempre devolve exatamente o que você dá!'),
(128, 'O que o gelo disse quando a festa esquentou?\nDerreto de alegria!'),
(129, 'O que a mochila disse para o estudante?\nVocê carrega minha vida, mas eu cargo a sua!'),
(130, 'O que o cinto disse para as calças?\nEu te sustento em qualquer situação!'),
(131, 'O que o limão disse ao açúcar?\nSem você, minha vida é amarga... quer dizer, azeda!'),
(132, 'Por que nunca se deve chorar sobre leite derramado?\nPorque o café fica salgado!'),
(133, 'O que o feijão disse ao arroz no casamento?\nJuntos somos um prato completo!'),
(134, 'O que a cadeira disse para a mesa?\nEu sempre estou do seu lado!'),
(135, 'O que o travesseiro sabe de você?\nTudo. Absolutamente tudo que você pensa antes de dormir!'),
(136, 'Por que todo mundo odeia o despertador?\nPorque ele é o único que bate e não apanha!'),
(137, 'O que a tesoura disse para o papel?\nVocê não tem escolha, vou te cortar de qualquer jeito!'),
(138, 'O que o pneu disse quando furou?\nMinha vida foi por água abaixo... quer dizer, por asfalto!'),
(139, 'A garrafa está meio cheia ou meio vazia?\nEstá certa — é hora de encher de novo!'),
(140, 'O que o orvalho disse para a grama de manhã?\nBom dia, vim refrescar sua vida!'),
(141, 'O que o canivete suíço disse para o abridor de lata?\nEu faço o seu trabalho e muito mais!'),
(142, 'Por que o poodle não gosta de piadas?\nPorque é muito fru-fru para isso!'),
(143, 'O que o papagaio disse para o espelho?\nVocê me copia!'),
(144, 'Por que a couve-flor ficou envergonhada?\nPorque a viram de maiô na salada!'),
(145, 'O que o Ás disse para o Dois?\nVocê nunca vai passar na minha frente!'),
(146, 'O que a bola de neve disse morro abaixo?\nIsso foi além do que eu esperava!'),
(147, 'Por que o guarda-chuva é sempre esquecido?\nPorque só lembram dele quando a chuva chega!'),
(148, 'O que o mapa disse para o GPS?\nAntes de você, as pessoas se perdiam com mais charme!'),
(149, 'Por que o trem nunca chega na hora?\nPorque ele tem seus próprios trilhos para seguir!');

